### ISSUE TITLE
Huggingface model inference (diagnosis prediction)

### ISSUE THREAD

**Issue by ashishakkumar** [bvanaken/clinical-outcome-prediction#16]
@bvanaken 
Can you please give an example code of how to using the model on HuggingFace you uploaded, to use for the diagnosis prediction. 
Moreover, may I ask where is the evaluation script  located for the diagnosis prediction and the other comparisons (BioBERT, ClinicalBERT,etc) 
Thank you

**Comment by bvanaken** [comment]
Hi,
For diagnosis prediction, I suggest using the model fine-tuned on the task. You can find it here: [https://huggingface.co/DATEXIS/CORe-clinical-diagnosis-prediction](https://huggingface.co/DATEXIS/CORe-clinical-diagnosis-prediction). 
The [base CORe model](https://huggingface.co/bvanaken/CORe-clinical-outcome-biobert-v1) is not fine-tuned on a specific task yet, but pre-trained using clinical outcome prediction. 

For evaluating the other models, you can simply use them as base models in the [doc_classification.py](experiments/doc_classification.py) script and you will get results after fine-tuning them to the task you want to evaluate.

Hope this helps!
Betty

**Comment by ashishakkumar** [comment]
Thank you
