### ISSUE TITLE
procedures.csv?

### ISSUE THREAD

**Issue by 2533245542** [bvanaken/clinical-outcome-prediction#6]
Hi,

I was trying the creation of admission notes but could not find this in mimic-iii. The closest I can get are just these two. In README, do you mean the ICD one?

<img width="259" alt="image" src="https://user-images.githubusercontent.com/28517073/149052021-48068331-6720-474c-8e4a-f4b3c8b8c677.png">

**Comment by bvanaken** [comment]
Hi,
yes, the PROCEDURES_ICD.csv is the correct file. I corrected that in the README. Thanks for the notice!
